spring:
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
  profiles:
    active: dev

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: auto
      table-format: "`%s`"
      column-format: "`%s`"
      property-format: "`%s`"
sa-token:
  # token名称 (同时也是cookie名称)
  token-name: token
  # token有效期，单位s, -1代表永不过期,3600*24*7代表7天
  timeout: 604800
  # token临时有效期 (指定时间内无操作就视为token过期) 单位: 秒
  active-timeout: -1
  # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
  is-concurrent: false
  # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
  is-share: true
  # token风格
  token-style: simple-uuid
  # 是否输出操作日志
  is-log: true

logging:
  level:
    com.github.qiu121: debug
    org.springframework: warn
    root: info
  pattern:
    dateformat: yyyy-MM-dd HH:mm:ss.SSS
